resource_group_name     = "TaskBoard"
resource_group_location = "North Europe"
app_service_plan_name   = "taskboard-service-plan"
app_service_name        = "taskboard"
sql_server_name         = "sqlserverntsonev"
sql_database_name       = "taskboarddb"
sql_user                = "4dm1n157r470r"
sql_user_pass           = "4-v3ry-53cr37-p455w0rd"
firewall_rule           = "TaskBoardFirewall"
github_repo             = "https://github.com/nikitsonev/Azure-Web-App-with-Database-TaskBoard"

